language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
  - "nightly"
install:
  - pip install -r requirements/development python-coveralls
script:
  - make testlocal
after_success:
  - coveralls
